docs/team/gwynethguo.md

- Add headings and some contribution details
- To have a well-documented data of my SE experience
- To list project contributions

Add Project Portfolio Page (PPP)

---

docs/_sass/minima/_base.scss
docs/index.md

- Change project name to MATHUTORING
- Change link of CI badge

Update site-wide settings

---

docs/UserGuide.md

Add command summary for User Guide
Resolves #44

Update user guide command summary

---

docs/UserGuide.md

* Edit feature: `add` student
* Edit feature: `delete` student
* Edit feature: `list` changed to `listStudents`
---
resolves #37 #38 #39

Edit feature list in UG: Add student, delete student and list students

---

docs/UserGuide.md

* Edit command format notes
---
resolves #46

Edit command format notes in UG

---

docs/DeveloperGuide.md

Added a few non-functional requirement. More to be added in the future.
resolves #16

Add non-functional requirement.

---

docs/UserGuide.md

Update user guide.
* Added quick start information.
* Changed description.
resolves #43 
resolves #45

Ug adapted v1

---

docs/UserGuide.md

Update user guide.
* Add to feature list: List student's tasks.
resolves #42

Add to feature list: List student's tasks

---

docs/AboutUs.md
docs/team/toh-xinyi.md

* Edit AboutUs.md to show each team member's PPP instead of JohnDoe.md
* Add additional content to Xin Yi's PPP

Edit AboutUs.md to show each team member's PPP instead of JohnDoe.md

---

docs/DeveloperGuide.md

- Add update student/task
- Add delete task
- Resolves #14

Add use case in developer guide

---

docs/DeveloperGuide.md

* Add and delete a few terminologies in glossary of DG
* Make small grammatical change to NFRs
---
resolves #17

Edit DG - Glossary

---

src/main/java/seedu/address/logic/Logic.java
src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/logic/commands/CheckCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/CheckCommandParser.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/PersonCard.java
src/main/java/seedu/address/ui/PersonListPanel.java
src/main/resources/view/DarkTheme.css
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/logic/commands/CheckCommandTest.java
src/test/java/seedu/address/logic/parser/CheckCommandParserTest.java

Fulfil the basic requirement about check.
Now key in check + index number, the respective student will be highlighted.
Part that related with task and score will be implemented after other teammates complete the functions.
Additional modify need to be made, including realtime update and focus scroll (if possible).
- resolves #64

Check function - version 1

---

src/main/resources/view/DarkTheme.css
src/main/resources/view/MainWindow.fxml
src/main/resources/view/PersonListPanel.fxml
src/main/resources/view/ScoreListCard.fxml
src/main/resources/view/ScoreListPanel.fxml
src/main/resources/view/TaskListCard.fxml
src/main/resources/view/TaskListPanel.fxml

Solved the cut text issue and refine the current UI.
close #82

Resolve the cut text problem and UI refinement

---

src/main/java/seedu/address/logic/commands/CheckCommand.java

Added logging information to CheckCommend to
detect the exceeding student index during check.

Add logging to CheckCommend

---

src/main/java/seedu/address/MainApp.java
src/main/java/seedu/address/commons/core/LogsCenter.java
src/main/java/seedu/address/logic/commands/AddScoreCommand.java
src/main/java/seedu/address/logic/commands/DeleteScoreCommand.java

- Add logging in the 'AddScoreCommand' and 'DeleteScoreCommand' class
- Update some logging messages from 'AddressBook' to 'MATHTUTORING'
- There is no `MainAppTest.java' class, and I am not sure do we need to write test for logging.

Add logging in the classes related to score command

---

src/main/java/seedu/address/model/score/Score.java
src/main/java/seedu/address/model/score/ScoreList.java

- Fix duplicate scores bug
- For each score, the score date is unique
resolves #105

Fix unique score list bugs

---

src/main/java/seedu/address/logic/commands/CommandResult.java
src/main/java/seedu/address/logic/commands/FilterCommand.java
src/main/java/seedu/address/logic/commands/SwitchCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/FilterCommandParser.java
src/main/java/seedu/address/model/tag/TagContainsKeywordsPredicate.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/ScoreListPanel.java
src/main/resources/view/DarkTheme.css
src/main/resources/view/ScoreListPanel.fxml

Filter by level that indicated by tag
close #109

Filter by level

---

src/main/java/seedu/address/commons/core/GuiSettings.java
src/main/java/seedu/address/logic/commands/CheckCommand.java
src/main/java/seedu/address/logic/commands/ClearCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/commands/ExitCommand.java
src/main/java/seedu/address/logic/commands/FilterCommand.java
src/main/java/seedu/address/model/tag/TagContainsKeywordsPredicate.java
src/main/java/seedu/address/ui/ScoreCard.java
src/main/java/seedu/address/ui/ScoreListPanel.java
src/main/java/seedu/address/ui/TaskListPanel.java
src/main/resources/view/DarkTheme.css
src/main/resources/view/MainWindow.fxml
src/main/resources/view/PersonListCard.fxml
src/main/resources/view/ScoreListCard.fxml
src/main/resources/view/ScoreListPanel.fxml
src/main/resources/view/TaskListCard.fxml
src/main/resources/view/TaskListPanel.fxml

Make the UI more responsive.
close #113

Final UI revamp

---

src/main/java/seedu/address/model/PdfConverter.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/score/ScoreList.java
src/main/java/seedu/address/ui/MainWindow.java

Fix bug where score list is not displayed properly on the UI upon delete
Resolves #121 
Resolves #127

Bugs:  deleteScore not showing the right UI and import/export window not closing

---

src/main/java/seedu/address/model/PdfConverter.java

Improve code quality in PdfConverter.java

---

docs/team/carrieli1015.md

Add a few lines to pass the weekly task.

Carrie - PPP draft

---

docs/team/astraxq.md
src/main/java/seedu/address/logic/commands/ExportDataCommand.java

Changed the default file directory to ```data/data.json```
Resolves #135

Export Bug Fix

---

src/main/java/seedu/address/logic/commands/ExportProgressCommand.java

Add uncommitted code in gwyneth-export-progress

---

src/main/java/seedu/address/logic/commands/DeleteScoreCommand.java
src/main/java/seedu/address/model/score/UniqueScoreList.java
src/main/java/seedu/address/ui/ScoreListPanel.java
src/test/java/seedu/address/logic/parser/DeleteScoreCommandParserTest.java
src/test/java/seedu/address/model/score/DateTest.java
src/test/java/seedu/address/model/score/ScoreTest.java
src/test/java/seedu/address/storage/JsonAdaptedScoreTest.java
src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
src/test/java/seedu/address/testutil/TypicalScores.java

* DateTest
* DeleteScoreCommandParserTest
* JsonAdaptedScoreTest
* JsonAdaptedStudentTest
* ScoreTest
* TypicalScores
* DeleteScoreCommand
* UniqueScoreList
* ScoreListPanel

Junit test and code quality

---

src/test/java/seedu/address/logic/commands/AddScoreCommandTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/DeleteScoreCommandTest.java
src/test/java/seedu/address/logic/commands/FilterCommandTest.java
src/test/java/seedu/address/logic/commands/SwitchCommandTest.java
src/test/java/seedu/address/logic/parser/AddScoreCommandParserTest.java
src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
src/test/java/seedu/address/logic/parser/MarkTaskCompleteCommandParserTest.java
src/test/java/seedu/address/logic/parser/MarkTaskInProgressCommandParserTest.java
src/test/java/seedu/address/logic/parser/MarkTaskLateCommandParserTest.java
src/test/java/seedu/address/model/tag/TagContainsKeywordsPredicateTest.java
src/test/java/seedu/address/testutil/TypicalIndexes.java
src/test/java/seedu/address/testutil/TypicalScores.java

Testing added:
1. filter command test
2. filter command parser test 
3. addScore command test
4. addScore command parser test
5. switch command test
6. deleteScore command test
7. TagContainsKeywordsPredicate test
8. markTaskComplete parser test
9. markTaskInProgress parser test
10. markTaskLate parser test

Junit testing 

---

src/main/java/seedu/address/logic/commands/CheckCommand.java
src/main/java/seedu/address/logic/commands/CommandResult.java
src/main/java/seedu/address/logic/commands/FilterCommand.java
src/main/java/seedu/address/logic/commands/SwitchCommand.java
src/main/java/seedu/address/logic/parser/CheckCommandParser.java
src/main/java/seedu/address/logic/parser/FilterCommandParser.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/tag/Tag.java
src/main/java/seedu/address/model/tag/TagContainsKeywordsPredicate.java
src/main/java/seedu/address/ui/ScoreCard.java
src/main/java/seedu/address/ui/ScoreListPanel.java
src/main/java/seedu/address/ui/StudentCard.java
src/main/java/seedu/address/ui/TaskCard.java
src/main/resources/view/DarkTheme.css
src/main/resources/view/Extensions.css
src/test/java/seedu/address/model/tag/TagTest.java

Carrie - Code quality improve

---

docs/team/gwynethguo.md

Update Gwyneth's PPP

---

docs/team/carrieli1015.md

Carrie final ppp

---

docs/team/carrieli1015.md

Remove more things from PPP
